spring:
  application:
    name: snowflake-api

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-service
            client-secret: fG7ulwLuFZ8wO5MueHbZq36m0KTpbG8T
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://localhost:8181/realms/w2m-disputes/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/w2m-disputes

w2m:
  rest:
    client:
      services:
        snowflake-client:
          service-url: https://mockserver.internal.w2m.com

server:
  port: 8081